apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-agency-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-agency
  template:
    metadata:
      labels:
        app: travel-agency
    spec:
      containers:
        - name: travel-agency-container
          image: 890iop/travel_agency:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
