export const tours = [
  {
    id: 1,
    title: 'Kyoto Cultural Escape',
    country: 'Japan',
    days: 5,
    price: 1240,
    rating: 4.9,
    reviews: 212,
    match: 98,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493780474015-ba834fd0ce2f?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1533050487297-09b450131914?q=80&w=900&auto=format&fit=crop',
    ],
    description:
      'Walk through centuries-old temples, wander bamboo groves, and experience a traditional tea ceremony on this immersive 5-day journey through Kyoto, Japan\u2019s cultural heart.',
    itinerary: [
      { day: 'Day 1', desc: 'Arrival + Fushimi Inari Shrine' },
      { day: 'Day 2', desc: 'Arashiyama Bamboo Grove + Kinkaku-ji' },
      { day: 'Day 3', desc: 'Gion District + Tea Ceremony' },
      { day: 'Day 4', desc: 'Nara day trip (deer park)' },
      { day: 'Day 5', desc: 'Nishiki Market + departure' },
    ],
    includes: ['4 nights hotel stay', 'Daily breakfast', 'Airport transfers', 'English-speaking guide', 'Entry tickets'],
  },
  {
    id: 2,
    title: 'Bali Coastal Getaway',
    country: 'Indonesia',
    days: 6,
    price: 890,
    rating: 4.7,
    reviews: 156,
    match: 94,
    image: 'https://images.unsplash.com/photo-1573790387438-4da905039392?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1573790387438-4da905039392?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?q=80&w=900&auto=format&fit=crop',
    ],
    description:
      'Relax on white-sand beaches, explore rice terraces, and enjoy Bali\u2019s laid-back coastal culture on this 6-day escape built for total relaxation.',
    itinerary: [
      { day: 'Day 1', desc: 'Arrival + Seminyak Beach' },
      { day: 'Day 2', desc: 'Ubud Rice Terraces + Monkey Forest' },
      { day: 'Day 3', desc: 'Snorkeling at Nusa Penida' },
      { day: 'Day 4', desc: 'Uluwatu Temple + sunset dinner' },
      { day: 'Day 5', desc: 'Spa day + free time' },
      { day: 'Day 6', desc: 'Departure' },
    ],
    includes: ['5 nights beachfront resort', 'Daily breakfast', 'Snorkeling trip', 'Private driver', 'Airport transfers'],
  },
  {
    id: 3,
    title: 'Swiss Alps Adventure',
    country: 'Switzerland',
    days: 7,
    price: 1650,
    rating: 4.9,
    reviews: 98,
    match: 91,
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1508189860359-777d945909ef?q=80&w=900&auto=format&fit=crop',
    ],
    description:
      'Ride scenic railways, hike alpine trails, and take in views of the Matterhorn on this 7-day adventure through the Swiss Alps.',
    itinerary: [
      { day: 'Day 1', desc: 'Arrival in Zurich' },
      { day: 'Day 2', desc: 'Lucerne + Mount Pilatus' },
      { day: 'Day 3', desc: 'Interlaken + Jungfraujoch' },
      { day: 'Day 4', desc: 'Zermatt + Matterhorn views' },
      { day: 'Day 5', desc: 'Alpine hiking trail' },
      { day: 'Day 6', desc: 'Lake Geneva + free time' },
      { day: 'Day 7', desc: 'Departure' },
    ],
    includes: ['6 nights hotel stay', 'Rail pass', 'Daily breakfast', 'Cable car tickets', 'English-speaking guide'],
  },
  {
    id: 4,
    title: "Cox's Bazar Beach Escape",
    country: 'Bangladesh',
    days: 3,
    price: 180,
    rating: 4.6,
    reviews: 340,
    match: 89,
    image: 'https://images.unsplash.com/photo-1503917988258-f87a78e3c995?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1503917988258-f87a78e3c995?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519821172141-b5d8342b3905?q=80&w=900&auto=format&fit=crop',
    ],
    description:
      'A quick 3-day beach break on the world\u2019s longest natural sea beach, with sunrise walks, fresh seafood, and time to unwind.',
    itinerary: [
      { day: 'Day 1', desc: 'Arrival + beach walk' },
      { day: 'Day 2', desc: 'Himchori waterfall + Inani beach' },
      { day: 'Day 3', desc: 'Free time + departure' },
    ],
    includes: ['2 nights hotel stay', 'Daily breakfast', 'Local transport', 'Beach guide'],
  },
  {
    id: 5,
    title: 'Sundarbans Wildlife Tour',
    country: 'Bangladesh',
    days: 2,
    price: 120,
    rating: 4.5,
    reviews: 87,
    match: 87,
    image: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1602491453631-e2a5ad90a131?q=80&w=900&auto=format&fit=crop',
    ],
    description:
      'A 2-day boat expedition into the world\u2019s largest mangrove forest, home to the Royal Bengal Tiger and abundant wildlife.',
    itinerary: [
      { day: 'Day 1', desc: 'Boat departure + mangrove cruise' },
      { day: 'Day 2', desc: 'Wildlife watch tower + return' },
    ],
    includes: ['1 night boat cabin', 'All meals', 'Forest permit', 'Guide'],
  },
  {
    id: 6,
    title: 'Paris City Highlights',
    country: 'France',
    days: 4,
    price: 980,
    rating: 4.8,
    reviews: 275,
    match: 96,
    image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=900&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1431274172761-fca41d930114?q=80&w=900&auto=format&fit=crop',
    ],
    description:
      'Hit the icons of Paris — the Eiffel Tower, the Louvre, and the Seine — on this 4-day city break through the City of Light.',
    itinerary: [
      { day: 'Day 1', desc: 'Arrival + Eiffel Tower' },
      { day: 'Day 2', desc: 'Louvre Museum + Seine river cruise' },
      { day: 'Day 3', desc: 'Montmartre + Sacr\u00e9-C\u0153ur' },
      { day: 'Day 4', desc: 'Free time + departure' },
    ],
    includes: ['3 nights hotel stay', 'Daily breakfast', 'Museum passes', 'River cruise ticket'],
  },
];

export const categories = ['All', 'Beach', 'Mountain', 'Cultural', 'Adventure', 'City Break'];

export const testimonials = [
  {
    name: 'Rafiq Ahmed',
    location: 'Dhaka, Bangladesh',
    stars: 5,
    text: 'Booking through VoyageAI was so easy. The Kyoto package matched exactly what we wanted, and support answered every question fast.',
  },
  {
    name: 'Sadia Islam',
    location: 'Chattogram, Bangladesh',
    stars: 5,
    text: 'The AI planner suggested a route we never would have thought of. Saved us both time and money on the Bali trip.',
  },
  {
    name: 'Tanvir Hasan',
    location: 'Sylhet, Bangladesh',
    stars: 4,
    text: 'Smooth checkout, clear pricing, no hidden fees. Will definitely book our next trip here too.',
  },
];
